"""Tests for the Story Agent."""

import pytest

from app.agents.story import STORY_SYSTEM_PROMPT, _quality_check_passes, generate_story


class TestStoryAgentHelpers:
    """Unit tests for Story Agent helpers."""

    def test_quality_check_requires_length(self):
        assert _quality_check_passes("# Short") is False
        assert _quality_check_passes("# " + "x" * 100) is True


class TestGenerateStory:
    """Integration-ish tests for generate_story with mocked LLMs."""

    @pytest.mark.asyncio
    async def test_generate_story_returns_ollama_narrative(self, monkeypatch):
        async def fake_ollama(messages: list) -> dict:
            assert messages[0]["content"] == STORY_SYSTEM_PROMPT
            return {
                "narrative": "# My Story\n\nIt was a meaningful week with many conversations.",
            }

        monkeypatch.setattr("app.agents.story._call_ollama_chat", fake_ollama)
        monkeypatch.setattr("app.agents.story._call_claude_chat", lambda x: (_ for _ in ()).throw(RuntimeError("no claude")))

        memories = [
            {"title": "Meeting", "summary": "Met with Sarah.", "created_at": "2024-07-01"},
            {"title": "Lunch", "summary": "Had lunch with Mike.", "created_at": "2024-07-02"},
        ]
        result = await generate_story("chronological", memories)

        assert "# My Story" in result
        assert "meaningful week" in result

    @pytest.mark.asyncio
    async def test_generate_story_falls_back_to_claude(self, monkeypatch):
        async def failing_ollama(messages: list) -> dict:
            raise RuntimeError("ollama unavailable")

        async def fake_claude(messages: list) -> dict:
            return {"narrative": "# Fallback Story\n\nGenerated by Claude."}

        monkeypatch.setattr("app.agents.story._call_ollama_chat", failing_ollama)
        monkeypatch.setattr("app.agents.story._call_claude_chat", fake_claude)
        monkeypatch.setenv("ANTHROPIC_API_KEY", "fake-key")

        memories = [{"title": "One", "summary": "One memory."}]
        result = await generate_story("curated", memories)

        assert "# Fallback Story" in result

    @pytest.mark.asyncio
    async def test_generate_story_returns_safe_fallback_for_empty_memories(self):
        result = await generate_story("digest", [])
        assert "No memories" in result
