"""Wiki viewer routes for OpenWiki Brains.

Serves Markdown files generated by OpenWiki (both the in-repo Code Brain and
the local Personal Brain) as a read-only browsable wiki.
"""

from fastapi import APIRouter, HTTPException, Query, Request, Response
from fastapi.responses import HTMLResponse
from pathlib import Path

router = APIRouter()

# Resolved wiki roots.
WIKI_ROOTS = {
    "code": Path(__file__).resolve().parents[2] / "openwiki",
    "personal": Path.home() / ".openwiki",
}


@router.get(
    "/wiki",
    response_class=HTMLResponse,
    summary="Wiki browser index",
    description="Renders an HTML index of all available OpenWiki brains and pages.",
)
async def wiki_index() -> str:
    """Render an HTML index page listing available wiki brains and pages."""
    sections = []
    for brain_id, root in WIKI_ROOTS.items():
        pages = _list_pages(root)
        section_items = "\n".join(
            f'<li><a href="/api/wiki/{brain_id}/pages/{p}">{p}</a></li>'
            for p in pages
        ) if pages else "<li><em>No pages found</em></li>"
        sections.append(
            f"""
            <section>
              <h2>{brain_id.title()} Brain</h2>
              <p><code>{root}</code></p>
              <ul>{section_items}</ul>
            </section>
            """
        )

    return _html_page(
        title="OpenWiki Brains",
        body="\n".join(sections),
    )


@router.get(
    "/wiki/{brain}",
    response_class=HTMLResponse,
    summary="List pages in a brain",
    description="Renders an HTML list of pages in the requested brain.",
)
async def wiki_brain_index(brain: str) -> str:
    """Render an HTML index for a single brain."""
    root = _resolve_root(brain)
    pages = _list_pages(root)
    items = "\n".join(
        f'<li><a href="/api/wiki/{brain}/pages/{p}">{p}</a></li>'
        for p in pages
    ) if pages else "<li><em>No pages found</em></li>"

    return _html_page(
        title=f"{brain.title()} Brain",
        body=f"""
        <p><a href="/api/wiki">← All brains</a></p>
        <p>Root: <code>{root}</code></p>
        <ul>{items}</ul>
        """,
    )


@router.get(
    "/wiki/{brain}/pages/{page_path:path}",
    summary="Get raw Markdown for a wiki page",
    description="Returns the raw Markdown content of a wiki page. Use ?format=html to render basic HTML.",
)
async def wiki_page(
    request: Request,
    brain: str,
    page_path: str,
    format: str = Query(default="markdown"),
) -> Response:
    """Return a wiki page as Markdown or a simple HTML preview.

    Args:
        request: FastAPI request object, used to inspect the raw URL path.
        brain: Which brain to read from ("code" or "personal").
        page_path: Relative path to the Markdown file.
        format: "markdown" returns raw Markdown; "html" returns a rendered preview.

    Returns:
        Response with raw Markdown or basic HTML preview of the requested page.

    Raises:
        404: If the page does not exist or is outside the wiki root.
    """
    # Reject traversal before FastAPI's path normalization collapses it.
    raw_path = request.url.path
    if "/.." in raw_path or raw_path.endswith("/.."):
        raise HTTPException(status_code=400, detail="Invalid page path")

    root = _resolve_root(brain)
    file_path = _resolve_page(root, page_path)

    try:
        content = file_path.read_text(encoding="utf-8")
    except FileNotFoundError:
        raise HTTPException(status_code=404, detail="Page not found")
    except OSError as exc:
        raise HTTPException(status_code=500, detail=f"Error reading page: {exc}")

    if format == "html":
        return Response(
            content=_html_page(
                title=page_path,
                body=f"""
                <p><a href="/api/wiki/{brain}">← {brain.title()} Brain</a></p>
                <hr>
                <pre>{_escape_html(content)}</pre>
                """,
            ),
            media_type="text/html",
        )

    return Response(content=content, media_type="text/plain")


def _resolve_root(brain: str) -> Path:
    """Resolve and validate the wiki root path."""
    if brain not in WIKI_ROOTS:
        raise HTTPException(
            status_code=400,
            detail=f"Unknown brain '{brain}'. Choose one of: code, personal.",
        )
    return WIKI_ROOTS[brain]


def _list_pages(root: Path) -> list[str]:
    """List all .md files under root, recursively, as relative paths."""
    if not root.exists():
        return []
    return sorted(
        str(path.relative_to(root)).replace("\\", "/")
        for path in root.rglob("*.md")
    )


def _resolve_page(root: Path, page_path: str) -> Path:
    """Resolve a page path and ensure it stays within the wiki root."""
    # Reject traversal in the original path string before normalization.
    normalized_input = page_path.replace("\\", "/")
    if ".." in normalized_input.split("/"):
        raise HTTPException(status_code=400, detail="Invalid page path")

    # Normalize separators and strip relative parts.
    safe_parts = [
        part
        for part in normalized_input.split("/")
        if part and part not in ("..", ".")
    ]
    if not safe_parts or any(part.startswith(".") for part in safe_parts):
        raise HTTPException(status_code=400, detail="Invalid page path")

    candidate = (root / "/".join(safe_parts)).resolve()
    if not str(candidate).startswith(str(root.resolve())):
        raise HTTPException(status_code=400, detail="Invalid page path")

    # If no extension provided, default to .md.
    if candidate.suffix != ".md":
        candidate = candidate.with_suffix(".md")

    return candidate


def _escape_html(text: str) -> str:
    """Escape HTML special characters."""
    return (
        text.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
    )


def _html_page(title: str, body: str) -> str:
    """Wrap body in a minimal HTML page."""
    return f"""<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{_escape_html(title)} — MEMIND OpenWiki</title>
  <style>
    body {{ font-family: system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; line-height: 1.6; max-width: 900px; margin: 2rem auto; padding: 0 1rem; color: #222; }}
    h1, h2, h3 {{ color: #111; }}
    a {{ color: #0066cc; text-decoration: none; }}
    a:hover {{ text-decoration: underline; }}
    code {{ background: #f4f4f4; padding: 0.15rem 0.35rem; border-radius: 4px; font-size: 0.9em; }}
    pre {{ background: #f8f8f8; padding: 1rem; overflow-x: auto; border-radius: 6px; }}
    ul {{ padding-left: 1.5rem; }}
    section {{ margin-bottom: 2rem; }}
  </style>
</head>
<body>
  <h1>{_escape_html(title)}</h1>
  {body}
</body>
</html>
"""
