"""Wiki viewer routes for OpenWiki Brains.

Serves Markdown files generated by OpenWiki (both the in-repo Code Brain and
the local Personal Brain) as a read-only, app-like browsable wiki.
"""

from fastapi import APIRouter, HTTPException, Query, Request, Response
from fastapi.responses import HTMLResponse
from pathlib import Path
from typing import Any

import frontmatter
import markdown

router = APIRouter()

# Resolved wiki roots.
WIKI_ROOTS = {
    "code": Path(__file__).resolve().parents[2] / "openwiki",
    "personal": Path.home() / ".openwiki",
}

# Markdown renderer with common extensions.
_markdown = markdown.Markdown(
    extensions=[
        "toc",
        "tables",
        "fenced_code",
        "nl2br",
    ],
    output_format="html",
)


@router.get(
    "/wiki",
    response_class=HTMLResponse,
    summary="Wiki browser index",
    description="Renders an HTML index of all available OpenWiki brains and pages.",
)
async def wiki_index() -> str:
    """Render an HTML index page listing available wiki brains and pages."""
    sections = []
    for brain_id, root in WIKI_ROOTS.items():
        tree = _page_tree(root)
        sections.append(
            _render_brain_section(
                brain_id=brain_id,
                root=root,
                tree=tree,
            )
        )

    return _app_page(
        brain=None,
        page_title="OpenWiki Brains",
        content="\n".join(sections),
    )


@router.get(
    "/wiki/{brain}",
    response_class=HTMLResponse,
    summary="List pages in a brain",
    description="Renders an HTML list of pages in the requested brain.",
)
async def wiki_brain_index(brain: str) -> str:
    """Render an HTML index for a single brain."""
    root = _resolve_root(brain)
    tree = _page_tree(root)

    content = f"""
    <div class="prose">
      <p class="text-muted">Root: <code>{root}</code></p>
      {_render_tree(tree, brain)}
    </div>
    """

    return _app_page(
        brain=brain,
        page_title=f"{brain.title()} Brain",
        content=content,
    )


@router.get(
    "/wiki/{brain}/pages/{page_path:path}",
    summary="Get a wiki page",
    description="Returns Markdown or a rendered HTML preview of a wiki page.",
)
async def wiki_page(
    request: Request,
    brain: str,
    page_path: str,
    format: str = Query(default="html"),
) -> Response:
    """Return a wiki page as Markdown or rendered HTML.

    Args:
        request: FastAPI request object, used to inspect the raw URL path.
        brain: Which brain to read from ("code" or "personal").
        page_path: Relative path to the Markdown file.
        format: "markdown" returns raw Markdown; "html" returns a rendered preview.

    Returns:
        Response with raw Markdown or HTML preview of the requested page.

    Raises:
        404: If the page does not exist or is outside the wiki root.
    """
    # Reject traversal before FastAPI's path normalization collapses it.
    raw_path = request.url.path
    if "/.." in raw_path or raw_path.endswith("/.."):
        raise HTTPException(status_code=400, detail="Invalid page path")

    root = _resolve_root(brain)
    file_path = _resolve_page(root, page_path)

    try:
        raw = file_path.read_text(encoding="utf-8")
    except FileNotFoundError:
        raise HTTPException(status_code=404, detail="Page not found")
    except OSError as exc:
        raise HTTPException(status_code=500, detail=f"Error reading page: {exc}")

    if format == "markdown":
        return Response(content=raw, media_type="text/plain")

    meta, html_body = _render_markdown_page(raw, brain, page_path)
    return Response(content=html_body, media_type="text/html")


def _resolve_root(brain: str) -> Path:
    """Resolve and validate the wiki root path."""
    if brain not in WIKI_ROOTS:
        raise HTTPException(
            status_code=400,
            detail=f"Unknown brain '{brain}'. Choose one of: code, personal.",
        )
    return WIKI_ROOTS[brain]


def _list_pages(root: Path) -> list[Path]:
    """List all .md files under root, recursively, as absolute Paths."""
    if not root.exists():
        return []
    return sorted(root.rglob("*.md"), key=lambda p: str(p.relative_to(root)).lower())


def _page_tree(root: Path) -> dict[str, Any]:
    """Build a nested folder tree of Markdown page metadata.

    Returns a dict mapping folder names to either a list of page metadata dicts
    (for files directly in that folder) or a recursive subtree dict.
    """
    tree: dict[str, Any] = {"_files": []}
    for page in _list_pages(root):
        rel = page.relative_to(root)
        parts = rel.parts
        current = tree
        for part in parts[:-1]:
            current = current.setdefault(part, {"_files": []})
        meta = _load_front_matter(page)
        current["_files"].append(
            {
                "path": "/".join(parts).replace("\\", "/"),
                "filename": parts[-1],
                "title": meta.get("title") or _title_from_filename(parts[-1]),
            }
        )
    return tree


def _render_tree(tree: dict[str, Any], brain: str) -> str:
    """Render a folder tree as nested unordered HTML lists."""
    items = []

    files = tree.get("_files", [])
    for file in sorted(files, key=lambda f: f["title"].lower()):
        items.append(
            f'<li class="page"><a href="/api/wiki/{brain}/pages/{file["path"]}">'
            f'{_escape_html(file["title"])}</a></li>'
        )

    folders = sorted(
        (name, subtree) for name, subtree in tree.items() if not name.startswith("_")
    )
    for folder_name, subtree in folders:
        subtree_html = _render_tree(subtree, brain)
        items.append(
            f'''
            <li class="folder">
              <span class="folder-name">📁 {_escape_html(folder_name)}</span>
              <ul>{subtree_html}</ul>
            </li>
            '''
        )

    return f"<ul>{''.join(items)}</ul>" if items else ""


def _render_brain_section(brain_id: str, root: Path, tree: dict[str, Any]) -> str:
    """Render one brain card on the home page."""
    pages = _flatten_tree_pages(tree)
    recent = sorted(
        pages,
        key=lambda p: (root / p["path"]).stat().st_mtime,
        reverse=True,
    )[:5]

    recent_items = "\n".join(
        f'<li><a href="/api/wiki/{brain_id}/pages/{p["path"]}">'
        f'{_escape_html(p["title"])}</a></li>'
        for p in recent
    ) if recent else "<li><em>No pages found</em></li>"

    tree_html = _render_tree(tree, brain_id) if tree.get("_files") or len(tree) > 1 else ""

    return f"""
    <section class="brain-card">
      <h2><a href="/api/wiki/{brain_id}">{brain_id.title()} Brain</a></h2>
      <p class="text-muted"><code>{root}</code> · {len(pages)} page(s)</p>
      <h3>Recent</h3>
      <ul>{recent_items}</ul>
      {f'<h3>All pages</h3>{tree_html}' if tree_html else ""}
    </section>
    """


def _flatten_tree_pages(tree: dict[str, Any]) -> list[dict[str, Any]]:
    """Flatten a page tree into a flat list of page metadata dicts."""
    pages: list[dict[str, Any]] = []
    pages.extend(tree.get("_files", []))
    for subtree in tree.values():
        if isinstance(subtree, dict):
            pages.extend(_flatten_tree_pages(subtree))
    return pages


def _resolve_page(root: Path, page_path: str) -> Path:
    """Resolve a page path and ensure it stays within the wiki root."""
    normalized_input = page_path.replace("\\", "/")
    if ".." in normalized_input.split("/"):
        raise HTTPException(status_code=400, detail="Invalid page path")

    safe_parts = [
        part
        for part in normalized_input.split("/")
        if part and part not in ("..", ".")
    ]
    if not safe_parts or any(part.startswith(".") for part in safe_parts):
        raise HTTPException(status_code=400, detail="Invalid page path")

    candidate = (root / "/".join(safe_parts)).resolve()
    if not str(candidate).startswith(str(root.resolve())):
        raise HTTPException(status_code=400, detail="Invalid page path")

    if candidate.suffix != ".md":
        candidate = candidate.with_suffix(".md")

    return candidate


def _load_front_matter(file_path: Path) -> dict[str, Any]:
    """Load YAML front matter from a Markdown file, returning metadata dict."""
    try:
        post = frontmatter.load(str(file_path))
        return post.metadata
    except Exception:
        return {}


def _render_markdown_page(raw: str, brain: str, page_path: str) -> tuple[dict[str, Any], str]:
    """Parse front matter and render Markdown body to HTML.

    Returns a tuple of (metadata, full_html_page).
    """
    try:
        post = frontmatter.loads(raw)
        meta = dict(post.metadata)
        body_md = post.content
    except Exception:
        meta = {}
        body_md = raw

    title = meta.get("title") or _title_from_filename(page_path)
    description = meta.get("description", "")
    tags = meta.get("tags", [])
    if isinstance(tags, str):
        tags = [tags]

    # Reset the Markdown instance to avoid idempotency issues across calls.
    _markdown.reset()
    rendered = _markdown.convert(body_md)

    meta_html = ""
    if description:
        meta_html += f'<p class="lead">{_escape_html(str(description))}</p>'
    if tags:
        tag_chips = " ".join(
            f'<span class="tag">{_escape_html(str(t))}</span>' for t in tags
        )
        meta_html += f'<div class="tags">{tag_chips}</div>'

    content = f"""
    <article class="prose">
      <h1>{_escape_html(str(title))}</h1>
      {meta_html}
      {rendered}
    </article>
    """

    return meta, _app_page(
        brain=brain,
        page_title=str(title),
        content=content,
        toc=_markdown.toc,
    )


def _title_from_filename(filename: str) -> str:
    """Generate a readable title from a Markdown filename."""
    stem = Path(filename).stem
    return stem.replace("-", " ").replace("_", " ").title()


def _escape_html(text: str) -> str:
    """Escape HTML special characters."""
    return (
        text.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
    )


def _app_page(
    brain: str | None,
    page_title: str,
    content: str,
    toc: str = "",
) -> str:
    """Wrap content in a full app-like HTML shell with sidebar and top bar."""
    brain_links = []
    for bid in WIKI_ROOTS:
        active = " active" if bid == brain else ""
        brain_links.append(
            f'<a class="nav-link{active}" href="/api/wiki/{bid}">{bid.title()} Brain</a>'
        )

    sidebar_tree = ""
    if brain:
        root = _resolve_root(brain)
        tree = _page_tree(root)
        sidebar_tree = _render_tree(tree, brain)

    toc_panel = f"""
    <aside class="toc">
      <div class="toc-title">On this page</div>
      {toc or '<p class="text-muted">No headings</p>'}
    </aside>
    """

    return f"""<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{_escape_html(page_title)} — MEMIND OpenWiki</title>
  <style>
    :root {{
      --bg: #f7f8fa;
      --panel: #ffffff;
      --text: #1f2328;
      --muted: #656d76;
      --border: #d1d5da;
      --accent: #0969da;
      --accent-hover: #0550ae;
      --tag-bg: #ddf4ff;
      --tag-text: #0969da;
      --sidebar-width: 260px;
      --toc-width: 220px;
      --max-content: 780px;
    }}
    * {{ box-sizing: border-box; }}
    body {{
      margin: 0;
      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif;
      background: var(--bg);
      color: var(--text);
      line-height: 1.6;
    }}
    .topbar {{
      position: fixed;
      inset: 0 0 auto 0;
      height: 56px;
      background: var(--panel);
      border-bottom: 1px solid var(--border);
      display: flex;
      align-items: center;
      padding: 0 1.25rem;
      z-index: 100;
    }}
    .topbar .brand {{
      font-weight: 700;
      font-size: 1.1rem;
      color: var(--text);
      text-decoration: none;
      margin-right: 2rem;
    }}
    .topbar nav {{
      display: flex;
      gap: 1rem;
    }}
    .nav-link {{
      color: var(--muted);
      text-decoration: none;
      font-size: 0.95rem;
      padding: 0.35rem 0.5rem;
      border-radius: 6px;
    }}
    .nav-link:hover, .nav-link.active {{
      color: var(--accent);
      background: #eef4ff;
    }}
    .layout {{
      display: grid;
      grid-template-columns: var(--sidebar-width) minmax(0, 1fr) var(--toc-width);
      gap: 1.5rem;
      max-width: 1400px;
      margin: 0 auto;
      padding: calc(56px + 1.5rem) 1.5rem 2rem;
    }}
    .sidebar {{
      position: sticky;
      top: calc(56px + 1.5rem);
      align-self: start;
      max-height: calc(100vh - 56px - 3rem);
      overflow-y: auto;
    }}
    .sidebar-title {{
      font-weight: 700;
      margin-bottom: 0.75rem;
      font-size: 0.85rem;
      text-transform: uppercase;
      letter-spacing: 0.05em;
      color: var(--muted);
    }}
    .sidebar ul {{
      list-style: none;
      margin: 0;
      padding: 0 0 0 0.75rem;
      border-left: 1px solid var(--border);
    }}
    .sidebar > ul {{
      padding-left: 0;
      border-left: none;
    }}
    .sidebar li {{
      margin: 0.15rem 0;
    }}
    .sidebar a {{
      display: block;
      color: var(--text);
      text-decoration: none;
      font-size: 0.9rem;
      padding: 0.25rem 0.5rem;
      border-radius: 4px;
    }}
    .sidebar a:hover {{
      background: #eef4ff;
      color: var(--accent);
    }}
    .folder-name {{
      font-weight: 600;
      font-size: 0.9rem;
      color: var(--muted);
      display: block;
      margin: 0.5rem 0 0.25rem;
    }}
    .main {{
      min-width: 0;
      background: var(--panel);
      border: 1px solid var(--border);
      border-radius: 10px;
      padding: 2rem;
    }}
    .prose {{
      max-width: var(--max-content);
    }}
    .prose h1, .prose h2, .prose h3 {{
      font-weight: 600;
      margin-top: 1.75rem;
      margin-bottom: 0.75rem;
      line-height: 1.3;
    }}
    .prose h1 {{ font-size: 2rem; border-bottom: 1px solid var(--border); padding-bottom: 0.5rem; }}
    .prose h2 {{ font-size: 1.5rem; }}
    .prose h3 {{ font-size: 1.2rem; }}
    .prose p {{ margin: 0.75rem 0; }}
    .prose ul, .prose ol {{ padding-left: 1.5rem; margin: 0.75rem 0; }}
    .prose li {{ margin: 0.25rem 0; }}
    .prose a {{ color: var(--accent); }}
    .prose a:hover {{ color: var(--accent-hover); }}
    .prose code {{
      background: #f0f2f5;
      padding: 0.15rem 0.35rem;
      border-radius: 4px;
      font-family: ui-monospace, SFMono-Regular, "SF Mono", Consolas, monospace;
      font-size: 0.9em;
    }}
    .prose pre {{
      background: #f5f7f9;
      padding: 1rem;
      border-radius: 8px;
      overflow-x: auto;
      border: 1px solid var(--border);
    }}
    .prose pre code {{ background: transparent; padding: 0; }}
    .prose table {{
      border-collapse: collapse;
      width: 100%;
      margin: 1rem 0;
    }}
    .prose th, .prose td {{
      border: 1px solid var(--border);
      padding: 0.5rem 0.75rem;
      text-align: left;
    }}
    .prose th {{ background: var(--bg); font-weight: 600; }}
    .lead {{ font-size: 1.15rem; color: var(--muted); margin-bottom: 1rem; }}
    .tags {{ display: flex; gap: 0.5rem; flex-wrap: wrap; margin: 0.75rem 0 1.25rem; }}
    .tag {{
      background: var(--tag-bg);
      color: var(--tag-text);
      padding: 0.2rem 0.6rem;
      border-radius: 999px;
      font-size: 0.8rem;
      font-weight: 500;
    }}
    .toc {{
      position: sticky;
      top: calc(56px + 1.5rem);
      align-self: start;
      font-size: 0.85rem;
    }}
    .toc-title {{
      font-weight: 700;
      color: var(--muted);
      margin-bottom: 0.75rem;
      text-transform: uppercase;
      letter-spacing: 0.05em;
    }}
    .toc ul {{ list-style: none; padding-left: 0; margin: 0; }}
    .toc li {{ margin: 0.35rem 0; }}
    .toc a {{ color: var(--muted); text-decoration: none; }}
    .toc a:hover {{ color: var(--accent); }}
    .brain-card {{
      background: var(--panel);
      border: 1px solid var(--border);
      border-radius: 10px;
      padding: 1.5rem;
      margin-bottom: 1.5rem;
    }}
    .brain-card h2 {{ margin-top: 0; }}
    .brain-card h2 a {{ color: var(--text); text-decoration: none; }}
    .brain-card h2 a:hover {{ color: var(--accent); }}
    .brain-card h3 {{
      font-size: 0.85rem;
      text-transform: uppercase;
      letter-spacing: 0.05em;
      color: var(--muted);
      margin: 1.25rem 0 0.5rem;
    }}
    .text-muted {{ color: var(--muted); }}
    @media (max-width: 1100px) {{
      .layout {{ grid-template-columns: var(--sidebar-width) minmax(0, 1fr); }}
      .toc {{ display: none; }}
    }}
    @media (max-width: 760px) {{
      .layout {{ display: block; padding-top: calc(56px + 1rem); }}
      .sidebar {{ position: static; margin-bottom: 1rem; }}
      .main {{ padding: 1rem; }}
    }}
  </style>
</head>
<body>
  <header class="topbar">
    <a class="brand" href="/api/wiki">MEMIND OpenWiki</a>
    <nav>{''.join(brain_links)}</nav>
  </header>

  <div class="layout">
    <aside class="sidebar">
      <div class="sidebar-title">Pages</div>
      {sidebar_tree if brain else f'<p class="text-muted">Select a brain to browse pages.</p>'}
    </aside>

    <main class="main">
      {content}
    </main>

    {toc_panel}
  </div>
</body>
</html>
"""
